### ISSUE TITLE
Requesting new api framework

### ISSUE THREAD

**Issue by ryanthompson591** [InteractiveAdvertisingBureau/AdCOM#16]
VPAID with a proxy video element.

VPAID implementations on web and mobile devices sometimes do not support the VPAID standard video element and instead proxy video element messages.

Why: 
1. On mobile proxying messages to a native player offers a more user friendly playback experience.
2. On Web some players video elements exist in separate iframes and cannot be passed to the vpaid ad.  It is standards compliant to pass a new video element and pass that to the VPAID ad. However, it is not a good user experience as many browsers will mute or pause the newly spawned video element.

Solution:
Let's have a standardized number for this type of non standard VPAID type.  This way if this environment is not suitable to the VPAID ad, this can be known at bid time.

**Comment by iantri** [comment]
Hi Ryan,

Sorry for the delay.  Proposals to expand the specification are discussed in the Programmatic Supply Chain Working Group (formerly OpenRTB) working group. Please bring a proposal to the working group -- some details below:

https://iabtechlab.com/blog/so-youd-like-to-propose-a-change-to-openrtb-adcom/
