### ISSUE TITLE
Redundant “If omitted, all types are assumed” for VideoPlacement.mime and AudioPlacement.mime

### ISSUE THREAD

**Issue by IntKecsk** [InteractiveAdvertisingBureau/AdCOM#21]
The VideoPlacement.mime and AudioPlacement.mime are marked as “required”, but there is a comment
“If omitted, all types are assumed” in the documentation for them.
If these fields are still required in AdCOM 1.0 (as are the equivalent fields in OpenRTB 2.5), then this comment is not needed.

**Comment by wittjill** [comment]
I'm leaving this for clarity. Thanks for point it out though.
