### ISSUE TITLE
user.eids should be object array?

### ISSUE THREAD

**Issue by yuzawa-san** [InteractiveAdvertisingBureau/AdCOM#24]
Should eids be an `object array` instead of an `object`? https://github.com/InteractiveAdvertisingBureau/AdCOM/blob/master/AdCOM%20v1.0%20FINAL.md#object--user-

It may live in the user.ext in 2.x, but it is an array in https://github.com/InteractiveAdvertisingBureau/openrtb/blob/master/extensions/2.x_official_extensions/eids.md

**Comment by iantri** [comment]
Hi @yuzawa-san -- I believe you are right, this appears to be an oversight. I will bring it to the attention of the group to be fixed.

**Comment by yuzawa-san** [comment]
What are the next steps here?

**Comment by wittjill** [comment]
updated: https://github.com/InteractiveAdvertisingBureau/AdCOM/pull/33
will go with this month's release
