### ISSUE TITLE
video/audio placement - Continuous playback

### ISSUE THREAD

**Issue by aronschatz** [InteractiveAdvertisingBureau/AdCOM#28]
I was going to submit a PR, but a discussion makes sense since this can be done in multiple ways.

The VAST working group wants to add a signal that the placement plays media continuously without user interaction needed to go to the next piece of content. The "macro" proposed was "continuous" which is fine.

AdCOM doesn't have this concept in the placement for video or audio.

There are, at least, two ways of doing this.

1. Add a new field for "continuous" playback to audio and video placements. It would be 0 or 1 (empty for unknown).
2. Add to List: Playback Methods an option for "Continuous Playback" with language explaining it. This is an interesting option since it spans audio and video and doesn't require a new field. However, I'm not sure if it is clean enough.

**Comment by aronschatz** [comment]
I was on the SIMID/VAST working group call and a point was brought up that continuous playback happens on the web with sites like Youtube. This means that playback methods would be used as originally intended and it would likely need a distinct signal for continuous play.

**Comment by jeffreycarlson** [comment]
+1 For other folk's easy reference, the current Playback Methods are below. It seems continuous playback needs a different location from `playmethod` as that value is just an integer and any of these existing methods could take place with a continuous playback (except 3 and 4 I believe).

[List: Playback Methods](https://github.com/InteractiveAdvertisingBureau/AdCOM/blob/master/AdCOM%20v1.0%20FINAL.md#list--playback-methods-)
The following table lists the various media playback methods.

Value	Definition
1	Initiates on Page Load with Sound On
2	Initiates on Page Load with Sound Off by Default
3	Initiates on Click with Sound On
4	Initiates on Mouse-Over with Sound On
5	Initiates on Entering Viewport with Sound On
6	Initiates on Entering Viewport with Sound Off by Default

**Comment by aronschatz** [comment]
I'm going to submit a PR for adding this as a new field to AdCOM in the video and audio placement section.

**Comment by aronschatz** [comment]
https://github.com/InteractiveAdvertisingBureau/AdCOM/pull/30 Closing this issue.
