### ISSUE TITLE
Samples: Media Response: undocumented Ad.cid field

### ISSUE THREAD

**Issue by mxmCherry** [InteractiveAdvertisingBureau/AdCOM#8]
[Appendix C: OpenRTB Interfaces](https://github.com/InteractiveAdvertisingBureau/AdCOM/blob/master/AdCOM%20v1.0%20FINAL.md#appendix-c--openrtb-interfaces-) / [Media Response](https://github.com/InteractiveAdvertisingBureau/AdCOM/blob/master/AdCOM%20v1.0%20FINAL.md#media-response-) undocumented `openrtb.response.seatbid[0].bid[0].media.ad.cid` field.

I believe, it moved to some other object or was just removed from `Ad` one. Can it be clarified, please? Or removed from sample JSON.

**Comment by drjbutler** [comment]
It was in the "Ad" object at some point, but removed from the spec.  Missed it in the JSON.  Good find; removed.
